#ifndef NETWORK_CONFIG_H
#define NETWORK_CONFIG_H

#include "models.h"

#define DISCOVERY_PORT 8081
#define DISCOVERY_REQUEST "DISCOVER_CHAT_SERVER"
#define DISCOVERY_RESPONSE_PREFIX "CHAT_SERVER"
#define NETWORK_MODE_TAILSCALE 1
#define NETWORK_MODE_LAN 2
#define NETWORK_MODE_MANUAL 3

#endif // NETWORK_CONFIG_H
